# Generated by Django 4.2.11 on 2024-06-19 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipify', '0003_foodimage_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='nutrients_absent',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='recipe',
            name='nutrients_present',
            field=models.TextField(null=True),
        ),
    ]
