# Generated by Django 4.2.11 on 2024-06-22 20:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recipify', '0005_recipe_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='DishImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/')),
                ('recipe', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='recipify.recipe')),
            ],
        ),
    ]
