version: '3'
services:
  app:
    build: .
    ports:
      - 8000:8000
    volumes:
      - ./recipify:/app/recipify
      - dbdata:/app/db.sqlite3
    networks:
      - app_network
  
volumes:
  dbdata: 
networks:
  app_network:
    driver: bridge