name: Django CI/CD Workflow

on:
  pull_request:
    branches: [ "main" ]

jobs:
  health-check-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Cache dependency
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip
      - name: Setup python environment
        uses: actions/setup-python@v3
        with:
          python-version: '3.11.9'
      - name: Check Python version
        run: python --version
      - name: Upgrade pip
        run: sudo pip3 install --upgrade pip
      - name: Install requirements.txt
        run: pip install -r requirements.txt
      - name: List files
        run: ls
